document.writeln("<html lang=\'en\'>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'UTF-8\'>");
document.writeln("		<title>Document</title>");
document.writeln("		<meta name=\'viewport\' content=\'width=device-width,initial-scale=1\'>");
document.writeln("		<link rel=\'stylesheet\' href=\'css/bootstrap.css\'>");
document.writeln("		<script src=\'js/jquery.min.js\'></script>");
document.writeln("		<script src=\'js/popper.min.js\'></script>");
document.writeln("    <script src=\'js/bootstrap.min.js\'></script>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/wyy_head.css\'>");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("    <div id=\'head\'  class=\'container-fluid\'>");
document.writeln("      <div>");
document.writeln("        <a href=\'#\'><img src=\'tu/1.png\' ></a>");
document.writeln("        <span><h3>网易云音乐</h3></span>");
document.writeln("        <span></span>");
document.writeln("        <span><h3>商城</h3></span>");
document.writeln("      </div>");
document.writeln("      <div id=\'head2\'>");
document.writeln("        <div>");
document.writeln("          <input type=\'text\' placeholder=\'H16真无线\'>");
document.writeln("          <ul>");
document.writeln("            <li><a style=\'color: #000;\' href=\'#\'>热门搜索</a></li>");
document.writeln("            <li><a style=\'color: #000;\' href=\'#\'>音乐人日历</a></li>");
document.writeln("            <li><a style=\'color: #000;\' href=\'#\'>哆啦A梦</a></li>");
document.writeln("            <li><a style=\'color: #000;\' href=\'#\'>音乐保温杯</a></li>");
document.writeln("            <li><a style=\'color: #000;\' href=\'#\'>蓝牙耳机</a></li>");
document.writeln("            <li><a style=\'color: #000;\' href=\'#\'>真无线</a></li>");
document.writeln("          </ul>");
document.writeln("        </div>");
document.writeln("        <div style=\'display: flex;align-items: center;\'>");
document.writeln("          <a href=\'#\'><img src=\'tu/2.png\' style=\'margin-left: 45px;width:42px;padding-bottom: 9px;\'></a>");
document.writeln("          <div id=\'d1\' style=\'position: relative;\'>");
document.writeln("            <img src=\'tu/3.jpg\' style=\'width: 30px;height: 30px;border-radius: 50%;margin-left: 20px;\'>");
document.writeln("            <ul style=\'list-style: none;font-size: 13px;border: 1px solid #ccc;position: absolute;width: 148px;background-color: #fff;top: 40px;left: -34px;border-radius: 5px;padding-left: 0;\'>");
document.writeln("              <li style=\'padding: 5px 20px;width: 100%;\'><a style=\'color: #000;width: 100%;\' href=\'#\'>我的订单</a></li>");
document.writeln("              <li style=\'padding: 5px 20px;\'><a style=\'color: #000;\' href=\'#\'>我的优惠劵</a></li>");
document.writeln("              <li style=\'padding: 5px 20px;\'><a style=\'color: #000;\' href=\'#\'>我的收货地址</a></li>");
document.writeln("              <li style=\'padding: 5px 20px;\'><a style=\'color: #000;\' href=\'#\'>网易云音乐首页</a></li>");
document.writeln("              <li style=\'padding: 5px 20px;\'><a style=\'color: #000;\' href=\'#\'>退出</a></li>");
document.writeln("            </ul>");
document.writeln("          </div>");
document.writeln("          <div id=\'d2\' style=\'width: 0;height: 0;border: 7px solid transparent;border-top-color: #000;margin-left: 10px;margin-top: 7px;\'></div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("	</body>");
document.writeln("</html>");